export const GET_HOME_PAGE_DATA = "GET_HOME_PAGE_DATA";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_SNACKBAR_SETTINGS = "SET_SNACKBAR_SETTINGS";
export const UPDATE_CARDS = "UPDATE_CARDS";
